### PR TITLE
add num_leaves dials object

### PR DESCRIPTION
**Pull request by joeycouse**
This PR adds the num_leaves dials object. This is an engine specific tuning parameter for 'lightgbm', it's probably the main parameter for controlling the complexity of lightbgm models since they grow leaf-wise instead of depth-wise [lightgbm doc](https://lightgbm.readthedocs.io/en/latest/Parameters-Tuning.html).

### CODE REVIEW

**Comment by hfrick** [comment]
Thank you @joeycouse ! I've put in a PR for parsnip so that the tidymodels machinery can pick up the new dials parameter.

@simonpcouch do you have opinions on this? In particular: any comments on the default range chosen here? 🙌

**Comment by jameslamb** [comment]
thanks for the `@` and context @simonpcouch !

I agree that `31` is probably too high of a floor. Knowing nothing about the size and shape of data, I think the range `num_leaves in [5, 100]` is a pretty good starting point!

Please also keep in mind this related discussion from @dfsnow: https://github.com/tidymodels/bonsai/issues/49. Some combinations of `max_depth` and `num_leaves` are impossible.

> with a few different aliases

LightGBM supports so many different aliases for parameters as a way to offer compatibility with a wide range of frameworks in different languages. I understand that that can make it challenging to configure, and has been a source of a lot of bugs and maintenance effort over the years 😭 

We have some internal mechanisms in the R and Python packages (and another in the core C/C++ code) for resolving aliases. If you'd like, in a separate issue thread, I'd be happy to provide some links to those and to have a discussion about the possibility of making some of those mechanisms part of the public API that you could just import.

**Comment by simonpcouch** [comment]
Thanks a lot for chiming in, @jameslamb!

Let's go with [5, 100], then.🏄‍♀️

Following up here, I'll revisit bonsai's 49 and open up an issue in bonsai related to the aliasing interface. Thanks for your willingness to discuss / make changes here!🙂

**Comment by hfrick** [comment]
Excellent, thanks for the input @jameslamb and thanks for the PR @joeycouse !

@simonpcouch I'll merge this PR and leave the parsnip one open until we've discussed release schedule etc 👍

**Review by simonpcouch — APPROVED** [review]

**Pull request merged**
